### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by lfogliantis**
Changed the GSL url which was outdated to a working version

### CODE REVIEW

**Comment by slinderman** [comment]
Thanks for catching this!

**Comment by lfogliantis** [comment]
my pleasure! Any suggestion on how to install openmp on ubuntu to use
parallel sampling, or a way to check if parallel sampling is enabled?

Il giorno gio 19 lug 2018 alle ore 20:45 Scott Linderman <
notifications@github.com> ha scritto:

**Comment by slinderman** [comment]
I believe OpenMP will automatically work on Ubuntu since it uses GNU
GCC/G++ by default.  You should just have to run `USE_OPENMP=True pip
install -e .` to tell it to compile with the parallel code.

Best,
Scott

**Comment by lfogliantis** [comment]
great thank you!

Il giorno gio 19 lug 2018 alle ore 20:54 Scott Linderman <
notifications@github.com> ha scritto:

**Pull request merged**
