### PR TITLE
Python 2/3 compatible

### PR DESCRIPTION
**Pull request by mmb90**

### CODE REVIEW

**Comment by jakirkham** [comment]
Any thoughts on this @slinderman? It would be nice to support Python 3. 😄

**Comment by mmb90** [comment]
Also, I've taken my [fork](https://github.com/Savvysherpa/pypolyagamma) and have prepared it to go up on [conda forge](https://github.com/conda-forge) as seen in this [PR](https://github.com/conda-forge/staged-recipes/pull/831). We can easily transfer the work that's gone on there to put this repo up instead. Also I've put my fork up on [PyPI](https://pypi.python.org) (since I have another [package](https://github.com/Savvysherpa/slda) that needs it) as [pypolyagamma-3](https://pypi.python.org/pypi/pypolyagamma-3) but I would gladly deprecate that to point back to yours.

**Comment by slinderman** [comment]
Thanks! Sorry for the slow response. I agree that Python 3 support would be
nice. I've just been away at a conference and a bit tied up. I'll take a
look today and get back to you. Again, really appreciate your interest.
Best,
Scott

**Comment by jakirkham** [comment]
No worries. Thanks for getting this in, @slinderman. Have fun at the conference. 😄

**Pull request merged**
